"""''

Revision ID: de3b6255a191
Revises: 
Create Date: 2024-07-31 19:18:15.134694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de3b6255a191'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('recibo', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recibo', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###
